# Generated by Django 4.1.7 on 2023-03-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='FOREST',
            field=models.IntegerField(null=True),
        ),
    ]
