# Generated by Django 4.1.7 on 2023-03-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_destinations_forest'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='IMAGES',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
