# Generated by Django 4.1.7 on 2023-03-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_destinations_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preference',
            field=models.CharField(choices=[('Goa', 'Goa'), ('Jaipur', 'Jaipur'), ('Shimla', 'Shimla'), ('Ranthambore', 'Ranthambore'), ('Mumbai', 'Mumbai')], max_length=100, null=True),
        ),
    ]
