# Generated by Django 4.1.7 on 2023-03-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='RATING',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='destinations',
            name='SNOW',
            field=models.IntegerField(null=True),
        ),
    ]
