# Generated by Django 4.1.7 on 2023-03-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_destinations_rating_destinations_snow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='IMAGES',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
